# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test1(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1552, 832)
        self.driver.find_element(By.LINK_TEXT, "Sign In").click()
        self.driver.find_element(By.NAME, "email").send_keys("jorgelonga@gmail.com")
        self.driver.find_element(By.NAME, "password").send_keys("choto123")
        self.driver.find_element(By.LINK_TEXT, "Register here").click()
        self.driver.find_element(By.NAME, "email").click()
        self.driver.find_element(By.NAME, "email").send_keys("sample@example.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("sample")
        self.driver.find_element(By.ID, "cpassword").click()
        self.driver.find_element(By.ID, "cpassword").send_keys("sample")
        self.driver.find_element(By.NAME, "firstName").click()
        self.driver.find_element(By.NAME, "firstName").send_keys("mateo")
        self.driver.find_element(By.NAME, "lastName").click()
        self.driver.find_element(By.NAME, "lastName").send_keys("lopez")
        self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(13) > input").click()
        self.driver.find_element(By.NAME, "email").send_keys("sample@example.com")
        self.driver.find_element(By.NAME, "password").send_keys("sample")
        self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input").click()
        user_name = self.driver.find_element(By.CLASS_NAME, "dropbtn").text
        assert "Sample" in user_name
        self.driver.find_element(By.ID, "searchBox").click()
        self.driver.find_element(By.ID, "searchBox").send_keys("dress")
        self.driver.find_element(By.ID, "searchButton").click()